### ISSUE TITLE
VueRouter is not found in vonic

### ISSUE THREAD

**Issue by wenjieguo** [wangdahoo/vonic#103]
ERROR in ./~/vonic/dist/vonic.min.js
Module not found: Error: Can't resolve 'VueRouter' in '/Users/xxx/code/mobile_site/node_modules/vonic/dist'
 @ ./~/vonic/dist/vonic.min.js 7:114-134
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8081 webpack/hot/dev-server ./src/main.js

**Comment by wangdahoo** [comment]
参考文档中的 webpack starter 项目

**Comment by zhengoogle** [comment]
不能出一个详细一点的集成文档吗
