### ISSUE TITLE
import Vonic from 'vonic'后就报错

### ISSUE THREAD

**Issue by acodercat** [wangdahoo/vonic#108]
ERROR in ./~/.2.0.0-beta.15@vonic/dist/vonic.min.js
Module not found: Error: Can't resolve 'Vue' in '/home/codercat/Desktop/uestc/node_modules/.2.0.0-beta.15@vonic/dist'
 @ ./~/.2.0.0-beta.15@vonic/dist/vonic.min.js 7:82-96
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js
ERROR in ./~/.2.0.0-beta.15@vonic/dist/vonic.min.js
Module not found: Error: Can't resolve 'VueRouter' in '/home/codercat/Desktop/uestc/node_modules/.2.0.0-beta.15@vonic/dist'
 @ ./~/.2.0.0-beta.15@vonic/dist/vonic.min.js 7:114-134
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

**Comment by wangdahoo** [comment]
@acodercat 请查看文档中关于如何通过`webpack`引入的章节
