### ISSUE TITLE
使用vue-cli创建，webpack构建(build)失败~

### ISSUE THREAD

**Issue by bbzz7** [wangdahoo/vonic#111]
![image](https://cloud.githubusercontent.com/assets/5621067/26827104/4f7fab72-4aee-11e7-9fda-75e4a955b907.png)

**Comment by bbzz7** [comment]
详细日志如下：
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@5.0.3
3 info using node@v8.0.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle vonic-template@2.0.0~prebuild: vonic-template@2.0.0
6 silly lifecycle vonic-template@2.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle vonic-template@2.0.0~build: vonic-template@2.0.0
8 verbose lifecycle vonic-template@2.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle vonic-template@2.0.0~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/frog/Desktop/庄宇公务/g高考20170605/app/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle vonic-template@2.0.0~build: CWD: /Users/frog/Desktop/庄宇公务/g高考20170605/app
11 silly lifecycle vonic-template@2.0.0~build: Args: [ '-c',
11 silly lifecycle   'NODE_ENV=production webpack --progress --hide-modules' ]
12 silly lifecycle vonic-template@2.0.0~build: Returned: code: 2  signal: null
13 info lifecycle vonic-template@2.0.0~build: Failed to exec build script
14 verbose stack Error: vonic-template@2.0.0 build: `NODE_ENV=production webpack --progress --hide-modules`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:887:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid vonic-template@2.0.0
16 verbose cwd /Users/frog/Desktop/项目/高考2017/app
17 verbose Darwin 16.6.0
18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
19 verbose node v8.0.0
20 verbose npm  v5.0.3
21 error code ELIFECYCLE
22 error errno 2
23 error vonic-template@2.0.0 build: `NODE_ENV=production webpack --progress --hide-modules`
23 error Exit status 2
24 error Failed at the vonic-template@2.0.0 build script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 2, true ]

**Comment by bbzz7** [comment]
构建环境如下：
webpack:2.6.1
node:8.0.0
npm:5.0.3
"vonic": "2.0.0-beta.13"

**Comment by wangdahoo** [comment]
@bbzz7 @hhhuaang https://wangdahoo.github.io/vonic-documents/#/?id=webpack

`使用 beta.15`
