### ISSUE TITLE
使用vue-cli创建，运行npm run dev报错

### ISSUE THREAD

**Issue by hhhuaang** [wangdahoo/vonic#112]
使用vue-cli创建项目
vue init webpack pro
然后用npm安装vonic
npm install vonic@2.0.0-beta.15
修改 index.html文件
修改main.js文件

```
const routes = [
    { path: '/', component: Hello }
]
Vue.use(Vonic.app, {
    routes: routes
})
```
最后运行 npm run dev 报错
![image](https://user-images.githubusercontent.com/10963105/26925330-fc6e4896-4c7b-11e7-9671-f08653611643.png)
我已近安装； vue-router

**Comment by wangdahoo** [comment]
@hhhuaang https://wangdahoo.github.io/vonic-documents/#/?id=webpack
