### ISSUE TITLE
Demo 在 iOS Safari 上使用手势返回上一页时播放两遍动画

### ISSUE THREAD

**Issue by wspl** [wangdahoo/vonic#114]
Repo 中所给的 Demo 在 iOS Safari 以及微信内置浏览器上，即自带向右滑动返回的浏览器内，向右滑动网页，网页正常返回，但是会播放两遍切换动画。

另外在 iOS 的 WKWebKit 上 `allowsBackForwardNavigationGestures = true` 的情况下也可以重现这个问题。

故寻求禁用该动画的方法，谢谢。

**Comment by zqgu2016** [comment]
@wspl 你是怎么解决的？

**Comment by wspl** [comment]
@zqgu2016 换个框架

**Comment by hasbug** [comment]
666
