### ISSUE TITLE
really awesome

### ISSUE THREAD

**Issue by leinue** [wangdahoo/vonic#12]

**Comment by wangdahoo** [comment]
;)

**Comment by vitorarjol** [comment]
@wangdahoo This lib is fantastic. It's so clean and easy to use. Thank you so much!!

**Comment by wangdahoo** [comment]
@vitorarjol There'll be a stable release next week, please keep watching and thanks ;)

**Comment by vitorarjol** [comment]
@wangdahoo Looking forward to the stable release! =D
