### ISSUE TITLE
路由按正常的引入没效果

### ISSUE THREAD

**Issue by changfu2015** [wangdahoo/vonic#125]
import Vue from 'vue'
import Vonic from 'vonic'
Vue.use(Vonic)
import layout from './lib/layout'
window.layout = window.layout || layout
import axios from 'axios'
Vue.prototype.$http = axios
import router from './router/index'
import store from 'store'

// 开发环境设置token
console.log(process.env.NODE_ENV)
var Cookie = require('./lib/cookie');
if (process.env.NODE_ENV === 'development') {
    Cookie.Cookie.set('token', '747d9c710b6a7dcc42ebc59682f8caf0');
}
console.log(router)

Vue.use(Vonic.app, {router,store}) 

./router/index文件
================================
import Vue from 'vue'
import VueRouter from 'vue-router'
Vue.use(VueRouter)
// 引入组件
// Page Components
import Index from '../index'

// Routes
const routes = [
  { path: '/allGoodsClassify/:type/', component: index},
]

const router = new VueRouter({
  routes: routes
})
export default router

**Comment by changfu2015** [comment]
打印的router app为null

**Comment by wangdahoo** [comment]
请看下文档再写
