### ISSUE TITLE
Tab的实现有非子路径实现的方案吗？

### ISSUE THREAD

**Issue by didi7** [wangdahoo/vonic#13]
最近接触了一个项目，需要用到具名路径传递参数，但是在TAB的实现中用子路径传递参数时存在问题，想问问目前的TAB有非子路径的实现方式吗？

**Comment by wangdahoo** [comment]
不配置path就行，详见 https://github.com/wangdahoo/vonic/blob/master/demo/components/TabBarWithoutRoutes.vue
