### ISSUE TITLE
我又来了，这次是vonic禁止了scroll事件

### ISSUE THREAD

**Issue by lanshengzhong** [wangdahoo/vonic#130]
window.addEventListener('scroll', ()=> {
      console.log(3) // 我不走 就不打印
    },false)
//在个各种生命周期都已经尝试过了》。。。。

// 解除禁止？？？
//removeEventListener 各种document window body  div
//touchmove各种document window body  div
//然后 
//很遗憾 
// 无效-----------------------------------------

**Comment by lanshengzhong** [comment]
打卡

**Comment by wangdahoo** [comment]
没有这个事件 是因为基于ionic的UI样式 window容器整个是100%宽 100%高 所以不会触发scroll
