### ISSUE TITLE
npm run dev 黄字警告

### ISSUE THREAD

**Issue by s51983** [wangdahoo/vonic#2]
WARNING in ./~/vue/dist/vue.common.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

请问如何处理

**Comment by wangdahoo** [comment]
不影响使用 下个版本中会处理掉 感谢你提的issue

**Comment by wangdahoo** [comment]
已解决
