### ISSUE TITLE
scroll组件怎么关闭无线加载

### ISSUE THREAD

**Issue by zengsuyi** [wangdahoo/vonic#22]

**Comment by zengsuyi** [comment]
手动关闭

**Comment by wangdahoo** [comment]
Scroll 查看demo，Vue Scroller 查看https://github.com/wangdahoo/vue-scroller/blob/master/demo/components/LoadMoreAndNoData.vue

**Comment by zengsuyi** [comment]
demo我有看，你demo写的是一直加载，没有关闭。我想在某个状态下手动关闭无限加载，不让它触发动作

**Comment by wangdahoo** [comment]
不设置 onInfinite 属性即可

**Comment by zengsuyi** [comment]
现在的需求就是我想设置之后加载到某个状态后手动关闭。现在不能实现？

**Comment by wangdahoo** [comment]
按现在的设计是，一旦后端返回没有更多数据可以加载的时候，前端调用其他组件来提示“无更多数据”，比如$toast之类的，而不是把onInfinite给去除了，毕竟“无更多数据”这个是有时效性的。

**Comment by zengsuyi** [comment]
懂你的意思，但现在就是如果不设计一个关闭动作，下面一直会显示正在加载。这样显示起来不友好。希望能加个手动关闭和开启。关闭后就显示无更多数据之类的。

**Comment by zengsuyi** [comment]
还有一个问题。vue的keepa-live应该放在哪里。不然我返回上个界面输入的东西全没了。不保存的话。

**Comment by wangdahoo** [comment]
```js
onInfinite(done) {
 // 调用done就可以关闭“正在加载”
  done()
}
```
