### ISSUE TITLE
API里的控件用法怎么用？

### ISSUE THREAD

**Issue by AngruMainyu** [wangdahoo/vonic#25]
HellowWorld可以运行了，但是API里的写法和HellowWorld的写法不一样啊，<template>标签是直接放body里吗？另外import {Tabs} from 'vonic'等语句究竟放哪？在JS和HTML文件里都报错：SyntaxError: import declarations may only appear at top level of a module

**Comment by wangdahoo** [comment]
@AngruMainyu 最新版本不需要在页面组件内import了 `Vue.use(Vonic.app, ...) `后默认注册为全局组件，工作忙碌，文档尚未更新。抱歉。

**Comment by AngruMainyu** [comment]
恩可以了，但现在有个问题组件VonInput好像不支持数据绑定？<von-input v-model="val"...>然后定义一个<md-button>{{val}}</md-button>这样，输入框改变值后按钮的text并未改变，但是用普通的<input v-model="val">是可以的，这是什么原因呢

**Comment by AngruMainyu** [comment]
又研究了下，von-input绑定数据用的不是v-model，应该是value.sync="username"这个吧，但还是不行，同样的在Vonic.Search组件里使用value.sync="keywords" 就可以绑定，但von-input就是不能绑定。。。

**Comment by wangdahoo** [comment]
@AngruMainyu https://github.com/wangdahoo/vonic/blob/master/demo/components/InputDefault.vue#L10
