### ISSUE TITLE
有wiki么？

### ISSUE THREAD

**Issue by lwjcjmx123** [wangdahoo/vonic#3]
另外想问一下。体积大不大。是不是要先引入ionic.css

**Comment by wangdahoo** [comment]
1、目前只有部分简约的文档 https://github.com/wangdahoo/vonic/blob/master/COMPONENTS.md，正式版发布后，会补全。2、js体积不是很大，组件打包后应该在百来K左右吧，按需引入的话，应该会更小。3、需要引入ionic.css，项目的ionic目录中是ionic 1.3.1版本的css文件，仅更改了主题色，后续会再考虑是否精简ionic.css这个较大的样式文件。

**Comment by Array-Huang** [comment]
我还以为ionic只能跟angular一起用，所以用了这套方案以后，跟 Cordova 相关的API也都可以用了么？

**Comment by wangdahoo** [comment]
这个项目只是用了ionic的样式而已，并不是用来构建Cordova项目的。

**Comment by peakcool** [comment]
https://github.com/wangdahoo/vonic/blob/master/COMPONENTS.md 简约的文档404 ～ ～，喜欢ionic，希望能有一份文档查看。
