### ISSUE TITLE
Which should I choose, vonic, vum, f7 or ionic?

### ISSUE THREAD

**Issue by virsir** [wangdahoo/vonic#34]
Thanks for opening source this wonderful tool, @wangdahoo 

What is the main differences between vonic and other frameworks? If I need to build a mobile app with web mainly running on iOS platform, and probably migrate to Android as well, what do you suggest?

Thanks again.

**Comment by wangdahoo** [comment]
Ionic aims at creating hybrid mobile app with web techniques. If you familiar with angular.js and your app mainly running on iOS platform, that's a nice option. And Vonic, vum are frameworks base on Vue.js to make mobile-like webapp. Choose them if you love Vue.js and component-driven development experience.
