### ISSUE TITLE
axios is not defined

### ISSUE THREAD

**Issue by vitorarjol** [wangdahoo/vonic#36]
I'm trying to use the 2.0 alpha version, but I can't get it to work =/

I always get the "axios is not defined" error, like the lib isn't included as a dependency.

Do you have any idea on this kind of error?

I'm thinking that's somethin related to the `module.exports.externals` from the webpack.config, but I don't know how to solve.

Thank you!

**Comment by wangdahoo** [comment]
https://jsfiddle.net/wangdahoo/c15mgqz8/

or 

https://github.com/wangdahoo/vonic-template/tree/2.x

**Comment by DarrenHou1993** [comment]
用vue-cli创建的项目没事、我自己的项目引入vonic的时候、还是这个错误呢。大神有知道啥原因吗。axios 这个库在使用vue-cli创建的项目中。能引入。但是没有找到关于引入的代码。 大神是否可指点一下。

**Comment by Su9Tail** [comment]
It didn't solve the problem perfectly.
