### ISSUE TITLE
Tabbar icons on switching landscape-portrait

### ISSUE THREAD

**Issue by vitorarjol** [wangdahoo/vonic#37]
When using Tabbar, if I switch the orientation of the device, the icons don't work properly.

If I reload the page the icons return to normal.

Here what looks like when I change the orientation using the chrome devtools (works the same way on a real device).

![image](https://cloud.githubusercontent.com/assets/4452447/22491455/acc95338-e80a-11e6-9c44-2299bf97f2a1.png)

Thanks!

**Comment by wangdahoo** [comment]
it seems that `Scalable` component should re-calculate boundaries on `orientationchange` event. Will fix later.

**Comment by wangdahoo** [comment]
will be released with v1.1.3
