### ISSUE TITLE
Swiper 不支持 点击事件吗。

### ISSUE THREAD

**Issue by Jot8** [wangdahoo/vonic#38]

**Comment by wangdahoo** [comment]
for example:

```html
<swiper-item>
  <h1 @click="onClick()">Item 1</h1>
</swiper-item>
```

**Comment by q1314wo9ai** [comment]
PC上是可以。但是移动端上我测试过了，/advanced/swiper/default ，在swiper-item允许滑动的时候是不会触发click的。

**Comment by wangdahoo** [comment]
@q1314wo9ai 看了一下，确实没法用@click。可用@touchstart代替。

**Comment by q1314wo9ai** [comment]
用@touchstart 会导致事件冒泡，能触发点击事件但是不能同时滑动。我这边可以用js去判断用户行为，但是会多写 很多杂乱的代码。能否在拖动Swiper时阻止click事件，阻止事件冒泡？

**Comment by wangdahoo** [comment]
现在可以了 `npm install vonic@2.0.0-alpha.15`
