### ISSUE TITLE
怎么集成vuex并注入store到子组件？

### ISSUE THREAD

**Issue by pansinm** [wangdahoo/vonic#41]
请问怎么注入store到子组件？

**Comment by psychokiller666** [comment]
同问

**Comment by wangdahoo** [comment]
2.0 正式版前给方案

**Comment by wangdahoo** [comment]
已支持 https://wangdahoo.github.io/vonic-documents/#/?id=vuex

`npm i vonic@2.0.0-beta.10 -S`
