### ISSUE TITLE
vonic2.0能否直接按组件的形式使用？或者vonic template怎么发布？

### ISSUE THREAD

**Issue by dengqianyi** [wangdahoo/vonic#42]
如题，我这边本身有一个vux的template，npm run build 后可以很方便的和flask一起发布。
但测试了下vonic的template的发布，发现npm run build后只有简单的index.html和build.js。
这个根本发布不了，所以想把vonic 放到vux的工程里，但报各种错误

* !!vue-style-loader!css-loader!./../../../node_modules/vue-loader/lib/style-rewriter?id=data-v-3d0942f6!sass-loader!./../../../node_modules/vux-loader/src/style-loader.js!./../../../node_modules/vue-loader/lib/selector?type=styles&index=0!./arrow.vue

比如这种，貌似是冲突了
感觉无解啊

**Comment by wangdahoo** [comment]
最终需要生成什么是你的webpack配置决定的，多个UI组件库一起用确实会麻烦一点，这里有个项目，希望能给你一些启发（vonic 1.0的）

https://github.com/wangdahoo/vonic-webpack-code-splitting

**Comment by dengqianyi** [comment]
今天尝试解决相关问题，发现问题蛮多的。
vonic的目标是做一个完整的spa开发框架，但我觉得可以先把它做成一个好用的组件。
plugin.js里的install，就只夹杂了router，楼主你还没有考虑vuex。这块需要一个可定制化的方法。

**Comment by wangdahoo** [comment]
@dengqianyi 嗯 正在考虑把router剥离出去
