### ISSUE TITLE
Scroll组件交互：实现多次加载数据后，没有更多数据的效果。

### ISSUE THREAD

**Issue by psychokiller666** [wangdahoo/vonic#43]
请问如何注销scroll滚动，

**Comment by psychokiller666** [comment]
<scroll class="windows-likelist" :on-infinite="onInfinite" v-ref:scroller style="top: 180px;">
code...
</scroll>

我用的是vue1.0 vm.$off(''onInfinite")  vm.$off(''infinite")，

试过都不行

**Comment by wangdahoo** [comment]
效果：
https://wangdahoo.github.io/vonic/docs/#/advanced/scroll

做法：通过slot分发新的UI元素替换原有的preload（1.0同理）

代码：https://github.com/wangdahoo/vonic/blob/master/demo/components/Scroll.vue#L11

**Comment by psychokiller666** [comment]
我填写了infinite 可是还是会继续监听，继续加载

**Comment by psychokiller666** [comment]
可以了谢谢！！！

**Comment by wangdahoo** [comment]
@psychokiller666 不客气
