### ISSUE TITLE
tabbar横竖屏切换的icon和text不对齐的bug还没修复么？

### ISSUE THREAD

**Issue by chenguose** [wangdahoo/vonic#45]

**Comment by chenguose** [comment]
正想使用来着，发现这个bug，心里一凉。请问作者什么时候可以修复啊

**Comment by wangdahoo** [comment]
1.0 还是 2.0？

**Comment by chenguose** [comment]
2.0，我发现你的tabbar的text是用了scalable组件，用css3去缩放字体大小，但是并没有考虑选屏的情况。我现在改了你的源码：
const scaleContent = (e, s) => {
    let scalable = e.querySelector('.von-scalable')
    let f=()=>{
      scalable.style.width = e.offsetWidth * s + 'px'
      scalable.style.height = e.offsetHeight * s + 'px'
      scalable.style.transform = 'scale(' + 1 / s + ', ' + 1 / s + ')'
      scalable.style.webkitTransform = 'scale(' + 1 / s + ', ' + 1/s + ')'
      scalable.style.left = '-' + e.offsetWidth / s + 'px'
      scalable.style.top = '-' + e.offsetHeight / s + 'px'
    }
    f()
    let isChange=false;
    window.addEventListener('orientationchange',function () {
      if(isChange)return;
      isChange=true;
      setTimeout(()=>{//延时是因为微信和qq浏览器的bug，旋转屏幕后属性不会马上更新
        f()
        isChange=false
      },200);
    })
  }

**Comment by wangdahoo** [comment]
旋转后重绘就好了 参见v1 分支代码 2.0忘记改了 稍后改一下

**Comment by chenguose** [comment]
我看了你的v1分支，不能用orientationchange，要用resize，不然的话你在微信 qq和pc端都会有问题的

**Comment by wangdahoo** [comment]
@chenguose 就是你代码里面提到的微信和qq浏览器的bug？晚上看下，感谢提醒。（贴代码可以用markdown ```，这样好看些)

**Comment by chenguose** [comment]
是的，用orientationchange的话要延时获取。pc端拉伸窗口也不会触发你的重绘，但你这个是移动端，也无所谓了。另外想加你有建qq群什么的吗？我想加你好友，我对比过觉得你的这套挺好用的。后面有问题我想请教你。

**Comment by wangdahoo** [comment]
@chenguose 有QQ群了
