### ISSUE TITLE
路由页面切换闪动

### ISSUE THREAD

**Issue by 1009208036** [wangdahoo/vonic#50]
在chrome浏览器上没有，但在手机上就会出现，页面切换后上一个页面会快速闪动一下后消失
就连demo中也有这个问题

**Comment by wangdahoo** [comment]
迁移到vue2.0后新的bug，但也比较不容易重现。beta前会解决。如有更多的关于机型、系统、浏览器、重新方式方面的信息，请尽量提供。

**Comment by 1009208036** [comment]
目前在iPhone上发现有这个问题，安卓上未测试，点击demo中的列表组件的最后一个模态窗，切换到模态窗的页面的时候会有这个现象，多试几次会出现，iPhone上的chrom，QQ内置，微信内置等浏览器均有这个现象，然后我移动调试发现是切换页面的时候会有一个元素删除，而且闪动出现的页面是上一个页面，貌似是因为移除上一个页面产生的

**Comment by wangdahoo** [comment]
谢谢你提供的信息，尽量在这周解决。

**Comment by 1009208036** [comment]
好的，期待大佬修复这个bug

**Comment by wangdahoo** [comment]
@1009208036 没有改transition代码，添加fastclick后好了很多。

**Comment by wangdahoo** [comment]
已修复
