### ISSUE TITLE
TODOs before 2.0 Beta

### ISSUE THREAD

**Issue by wangdahoo** [wangdahoo/vonic#54]
# 备忘

- [x] nav state manual updating
- [x] nav transition optimization
- [x] swipe re-write
- [x] badge、badge on tabbar
- [ ] vuex samples

**Comment by vitorarjol** [comment]
Hi @wangdahoo! I know that the vuex samples are in your roadmap, but is there any simple way to use vuex with vonic right now? Thanks!

**Comment by wangdahoo** [comment]
close due to 2.0.0-beta.6 released.
