### ISSUE TITLE
悬浮标签输入框输入问题

### ISSUE THREAD

**Issue by 1009208036** [wangdahoo/vonic#55]
问题如下gif图所示
![fdghfdh](https://cloud.githubusercontent.com/assets/11371523/23009573/b5f6a412-f451-11e6-83a8-e801adec2564.gif)

**Comment by 1009208036** [comment]
后来试了一下普通的输入框，发现也有一样的问题

**Comment by wangdahoo** [comment]
@1009208036 今天或明天早上会发版本

**Comment by 1009208036** [comment]
好的~开关也有一点问题，改变开关的值不会触发开关改变
