### ISSUE TITLE
npm run build的时候报出UglifyJs SyntaxError: Unexpected token: operator (>)

### ISSUE THREAD

**Issue by psychokiller666** [wangdahoo/vonic#58]
你好，是这样的。我用了vue-cli https://github.com/vuejs-templates/webpack 构造的项目结构。

并且安装引用了最新的vonic@2.0.0-alpha.13

在npm run dev ，没有任何问题。

在发布的时候npm run build 提示了

ERROR in static/js/vendor.578243cbed6d92063e22.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [./~/vonic/src/services/utils.js:1,0][static/js/vendor.578243cbed6d92063e22.js:8929,37]

很没头绪。

**Comment by wangdahoo** [comment]
你好，是这样的。看这个就行了 https://github.com/wangdahoo/vonic-webpack-demo

**Comment by psychokiller666** [comment]
好的，我试试看！
