### ISSUE TITLE
不支持vue2.0？

### ISSUE THREAD

**Issue by Sinboo** [wangdahoo/vonic#6]
不支持最新的vue2.0吗？

**Comment by wangdahoo** [comment]
later...

**Comment by zzf88521** [comment]
大兄弟，超喜欢你的Vonic，啥时候出2.0，一出来我立马就用！

**Comment by wangdahoo** [comment]
@zzf88521 一月份吧;)

**Comment by peakcool** [comment]
如果真是一月份2.0真是太好了，别水啊哥们儿。

**Comment by jarden-liu** [comment]
虎哥，2.0最快什么时候上啊？

**Comment by morganwu** [comment]
非常感谢作者的共享精神和高效率工作，建议适当的时候放个支付宝帐号，让用户表示下支持

**Comment by wminjay** [comment]
@wangdahoo 一月出了2.0，我直播吃屎

**Comment by LuoLiangDSGA** [comment]
坐等2.0...希望快点

**Comment by morganwu** [comment]
@wminjay 为了激楼主你这也太拼了吧

**Comment by zengsuyi** [comment]
快上2.0啊   我现在用1.0出现个问题    this.instances[delegateId].show is not a function  modal组件 是什么问题啊

**Comment by xiaohui-zhangxh** [comment]
@wangdahoo 看来大家都希望出2.0，要不要大家一起来迁移？

**Comment by xiaolovecai** [comment]
@wminjay 我提供shi

**Comment by liadbiz** [comment]
@wangdahoo 大哥加油～学生党期待v2版本～
btw, 好像开发者就您一个，大哥不需要大家的力量吗？

**Comment by shmy** [comment]
支持

**Comment by benyu** [comment]
为什么我用所有组件都提示： <组件名> - did you register the component correctly?
无法正常显示，但是只有一个 md-button 可以正确显示？

**Comment by mcmf** [comment]
2.0 何时?

**Comment by wangdahoo** [comment]
@mcmf 关注2.0分支，beta版快了

**Comment by YAN7** [comment]
虎哥，你这个组件库做的真的超帅啊，不过现在新项目基本都用2.0了，希望能快点出2.0版本，感激感激啊

**Comment by wangdahoo** [comment]
@wminjay https://unpkg.com/vonic@2.0.0-alpha.1/dist/vonic.min.js 也不知道这算不算哦？

**Comment by vitorarjol** [comment]
Thank you @wangdahoo !

**Comment by jarden-liu** [comment]
@wangdahoo 虎哥，2.0有发布到npm上面去吗？

**Comment by wangdahoo** [comment]
@jarden-liu `npm install vonic@2.0.0-alpha.6` 还在写文档和 sample code.
