### ISSUE TITLE
tabbar 不能根据输入的路由，动态选中对应菜单

### ISSUE THREAD

**Issue by jackshenjunkai** [wangdahoo/vonic#62]
![image](https://cloud.githubusercontent.com/assets/17916158/23327890/5dd22086-fb4f-11e6-8b87-a82aca3907a7.png)
如上用户进入页面需要默认选中【我的】菜单，但是tabbar总是默认选中第一个菜单项，实际页面内容是正确的，只有tabbar选中的菜单项不对应，希望添加一个默认激活菜单索引的参数，可以让开发者自由选择默认激活那一个菜单项

**Comment by phpcxy** [comment]
我也刚踩完这个坑，楼主请看https://github.com/wangdahoo/vonic/blob/master/demo/components/tabbar/Cart.vue

有个`v-tabbar-menu-index` 属性
