### ISSUE TITLE
Tabbar与modal混用时的bug

### ISSUE THREAD

**Issue by webees** [wangdahoo/vonic#66]
主入口app.vue，这里设置了Tabbar，然后再在这个app.vue渲染其他子页面
```
<template>
  <div class="page" v-tabbar="{'menus': menus, menuColor: '#808080', activeMenuColor: '#D0AE81', onMenuClick: menuClicked}">
    <router-view class="child-view"></router-view>
  </div>
</template>
```
然后子页面调用了一个modal，假设这个子页面是   sub.vue，弹出了 modal.vue，

通过Tabbar切换到 sub.vue ，再点击按钮弹出 modal.vue，正常！
但是在 sub.vue刷新页面，点击按钮弹出 modal.vue，不正常。

原因是dom插入的位置不对。正常情况下`<div von-modal="" class="modal-backdrop hide">`应该在`<div class="tabbar">`之后，但是刷新页面时候却不是这样。通过tabbar切换是才会恢复正常。

目前我这里的解决办法是tabbar的z-index: 2;

**Comment by wangdahoo** [comment]
sub.vue是子路由页面组件 还是 子路由页面组件内由 $modal 加载的 modalContentComponent ? @webees

**Comment by wangdahoo** [comment]
$modal 加载的 component dom 都不会在 `[von-app]` 范围内

**Comment by webees** [comment]
@wangdahoo 不好意思，打字打快了。这个sub.vue是子路由页面，这个子路由页面加载了modal.vue模态框。这个模态框在刷新加载页面时候dom插入的位置由于先于tabbar，导致modal-backdrop无效。

**Comment by webees** [comment]
刷新页面后，弹出模态框有问题。切换页面后再回来弹出模态框正常。

**Comment by wangdahoo** [comment]
好的 回头看一下

**Comment by wangdahoo** [comment]
@webees 这个问题能给个详细的代码例子吗？

**Comment by wangdahoo** [comment]
这个没有详细的代码例子的话，先close了
