### ISSUE TITLE
License info

### ISSUE THREAD

**Issue by clairetsai818** [wangdahoo/vonic#75]
Hi! I am a member of [CDNJS](https://github.com/cdnjs/cdnjs).
We'd like to add this wonderful lib to our CDN but couldn't find any info about the license. Could you please confirm the license for us? Thanks!
related issue: https://github.com/cdnjs/cdnjs/issues/10649

**Comment by wangdahoo** [comment]
@clairetsai818 as your wish. https://github.com/wangdahoo/vonic/blob/master/LICENSE

**Comment by clairetsai818** [comment]
@wangdahoo Thanks a lot!
