### ISSUE TITLE
5s下面实例demo打开展示白屏

### ISSUE THREAD

**Issue by Chaunjie** [wangdahoo/vonic#79]
iphone 5s下面实例demo打开展示白屏，pc访问没问题 @wangdahoo

**Comment by Chaunjie** [comment]
uc/qq/微信浏览器访问都是如此
![Uploading 568EFBC757384EEEBB1042FEEDF44B1D.png…]()

**Comment by wangdahoo** [comment]
亲测 5s 及 5s 下最新版微信都没问题 （但目前没有支持非现代浏览器的计划）。另，再提类似issue请注明系统版本，浏览器版本，是否为应用内定制的webview等信息。
