### ISSUE TITLE
vonic 加入  组件von-input  控制台报错

### ISSUE THREAD

**Issue by github2015wlj** [wangdahoo/vonic#83]
[Vue warn]: Missing required prop: value (found in component: <von-input>)   
  
代码如下：
<template>
  <div class="page has-navbar" v-nav="{title: 'About', showBackButton: true}">
    <div class="page-content text-center">
      <von-input
        type="text"
        v-model="username"
        placeholder="用户名/手机/邮箱"
        label="用户名"
        >
      </von-input>
      <span>{{username}}</span>
    </div>
  </div>
</template>
<script>
  import {VonInput} from 'vonic'
  export default {
    data() {
      return {
        username:'dfgfd'
      }
    },
    components: {
      VonInput
    },
    methods: {

    }
  }
</script>

**Comment by wangdahoo** [comment]
请查阅文档站
