### ISSUE TITLE
$app.settitle是否应该在created或者mounted方法的时候就可以调取到，目前应该只有通过点击才能调取

### ISSUE THREAD

**Issue by youngchen1987** [wangdahoo/vonic#84]
$app.settitle是否应该在created或者mounted方法的时候就可以调取到，目前应该只有通过点击才能调取
并且我在源码中搜索也没有找到这个是在什么位置写的  可否告知一下?

**Comment by youngchen1987** [comment]
$app 在vue生命周期的哪个阶段?

**Comment by wangdahoo** [comment]
`<von-app>` 加载完成后方可
