### ISSUE TITLE
请求官网文档移除 Google 字体

### ISSUE THREAD

**Issue by evolutionjay** [wangdahoo/vonic#85]
<img width="554" alt="2017-03-27 10 43 43" src="https://cloud.githubusercontent.com/assets/4468540/24338753/50c8d18a-12da-11e7-88d5-45cf8d480e29.png">

如图，国内就是那个屌样，即使我用 SSR 也没办法加载出来。
改了HOSTS 也没办法加载出来，
难道要改 127.0.0.1 屏蔽大法？

**Comment by sinchang** [comment]
@wangdahoo  just change ` fonts.googleapis.com` to `fonts.css.network`, more detail in https://ttt.tt/185/

**Comment by wangdahoo** [comment]
已修改。 谢谢 @sinchang
