### ISSUE TITLE
$dialog.show函数执行第二次时会报异常

### ISSUE THREAD

**Issue by pansinm** [wangdahoo/vonic#87]
![dialog-show](https://cloud.githubusercontent.com/assets/5510633/24484104/0b79cbbe-152f-11e7-8c4e-6375d26f803d.png)

**Comment by wangdahoo** [comment]
what's your point?

**Comment by pansinm** [comment]
```javascript
$dialog.confirm({
  theme: 'ios',
  title: '测试？',
  cancelText: '取消',
  okText: '确认'
}).then(console.log)
```

这段代码指定第二次的时候会报异常：
Cannot read property 'then' of undefined

**Comment by wangdahoo** [comment]
那我回头改成连续两次执行的情况下，报Warning吧

**Comment by pansinm** [comment]
可能是我没描述清楚，下面这段代码是会抛异常的
```javascript
$dialog.confirm({
  theme: 'ios',
  title: '测试1？',
  cancelText: '取消',
  okText: '确认'
}).then(function(result) {
  setTimeout(function() {
    $dialog.confirm({
      theme: 'ios',
      title: '测试2？',
      cancelText: '取消',
      okText: '确认'
    }).then(console.log);
  }, 300);
});
```

https://jsfiddle.net/w21dyesn/2/

**Comment by wangdahoo** [comment]
@pansinm 哦 天哪 改出bug来了
![timg](https://cloud.githubusercontent.com/assets/8207553/24555756/d1c67692-1664-11e7-85f9-9d2fef47af12.jpeg)
