### ISSUE TITLE
调用$loading.show()之后，调用$toast.show()  toast 框会一闪而过

### ISSUE THREAD

**Issue by endian86** [wangdahoo/vonic#88]
代码逻辑是:
$loading.show('加载中..');
ajax请求，
$loading.hide();

$toast.show('错误码');

发现toast总是一闪而过

**Comment by wangdahoo** [comment]
这是因为 `$loading.hide()` fade动效本身有300ms的时间。你其实只要这样就可以了：

演示：
https://wangdahoo.github.io/vonic-documents/demo/#/ToastAndLoading

代码：
https://github.com/wangdahoo/vonic-documents/blob/master/demo/index.js#L496
