### ISSUE TITLE
内部组件使用 vuex 问题

### ISSUE THREAD

**Issue by toniol** [wangdahoo/vonic#89]

**Comment by toniol** [comment]
内部组件使用`this.$store`输出`undefined`，store 好像并没有注入到全局
导出`store`
```javascript
export default new Vuex.Store({
  state,
  getters,
  actions,
  mutations
})
```
`main.js`中注入
```javascript
import store from './store/'

Vue.use(Vonic.app, {
  routes,
  store
})
````

**Comment by wangdahoo** [comment]
参考：
https://github.com/wangdahoo/vonic-documents/blob/master/demo/vuex/counter.html#L108

演示：
https://wangdahoo.github.io/vonic-documents/demo/vuex/counter.html
