### ISSUE TITLE
English Documentation

### ISSUE THREAD

**Issue by vinicius73** [wangdahoo/vonic#9]
This is a very nice project, but is hard to use and share because they doc not is in english

**Comment by wangdahoo** [comment]
later after a stable release. thanks for reminding.

**Comment by vinicius73** [comment]
Awesome!

**Comment by ganyusheng520** [comment]
干得漂亮

**Comment by wangdahoo** [comment]
@vinicius73 https://wangdahoo.github.io/vonic-doc/en/
