### ISSUE TITLE
【建议】DatePicker 使用v-model="date"双向绑定，date修改后组件显示不变

### ISSUE THREAD

**Issue by 0604hx** [wangdahoo/vonic#99]
RT。

父组件 date 属性与 DatePicker 双向绑定，在父组件中修改 date 后 DatePicker 显示的日期没有改变，需手动调用以下代码方能更新
```
this.$refs['datePicker'].formatedDate = d
```

建议下个版本可以改成自动修改。

谢谢！

**Comment by wangdahoo** [comment]
可以的啊

https://wangdahoo.github.io/vonic-documents/demo/#/Datepicker

**Comment by wangdahoo** [comment]
哦 父组件... 这是业务代码，朋友
